services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    image: raakz/devops-for-developers-project-74
    depends_on:
      - db
    environment:
      - DATABASE_NAME=blog_development
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - NODE_ENV=production

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: